[package]
name = "plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
iced = "0.13.1"
iced_futures = "0.13.2"
magic = "0.16.2"
anyhow = "1.0.98"
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.19"
